cartpole:
  rl_trainers:
    ros__parameters:
      metadata:
        mode: train              # "train" or "eval"
        task: cartpole_vec      # must match entry_point in setup.py # 'cartpole' or 'cartpole_vec'
        artifacts_dir: /app/src/cartpole/data
      algorithm:
        name: ppo                # must match trained algo
        device: auto             # "cpu" | "cuda" | "auto"
        policy: MlpPolicy        # must match trained policy
      train:
        total_timesteps: 100000  # only used if mode == "train"
        save_freq: 100000
        progress: true
        n_envs: 8  
      eval:
        episodes: 10             # only used if mode == "eval"
        deterministic: true
        render: false
        video: false
        model_path: "/app/src/cartpole/data/model/PPO/custom_cartpole_20250909_20_55"
        n_envs: 1
      ppo:
        learning_rate: 3.0e-4
        n_steps: 2048
        batch_size: 256
        n_epochs: 10
        gamma: 0.99
        gae_lambda: 0.95
        clip_range: 0.2
        ent_coef: 0.0
        vf_coef: 0.5
        max_grad_norm: 0.5
        normalize_advantage: true
        use_sde: false
        sde_sample_freq: -1
        target_kl: -1.0
        stats_window_size: 100
        seed: 0
        tensorboard: true
        policy_kwargs: "{}"

cartpole_a2c:
  rl_trainers:
    ros__parameters:
      metadata:
        mode: train              # "train" or "eval"
        task: cartpole      # must match entry_point in setup.py # 'cartpole' or 'cartpole_vec'
        artifacts_dir: /app/src/cartpole/data
      algorithm:
        name: a2c                # must match trained algo
        device: cpu             # "cpu" | "cuda" | "auto"
        policy: MlpPolicy        # must match trained policy
      train:
        total_timesteps: 100000  # only used if mode == "train"
        save_freq: 100000
        progress: true
        n_envs: 8  
      eval:
        episodes: 10             # only used if mode == "eval"
        deterministic: true
        render: false
        video: false
        model_path: "/app/src/cartpole/data/model/A2C/cartpole_20250915_22_57"
        n_envs: 1
      a2c:
        learning_rate: 7.0e-4
        n_steps: 5
        gamma: 0.99
        gae_lambda: 1.0
        ent_coef: 0.0
        vf_coef: 0.25
        max_grad_norm: 0.5
        rms_prop_eps: 1.0e-5
        use_rms_prop: true
        normalize_advantage: true
        seed: 0
        tensorboard: true
        policy_kwargs: "{}"
